
version: 2
updates:

  - package-ecosystem: pip
    directory: "/gui"
    schedule:
      interval: daily
      time: "04:00"
    groups:
      python-packages:
        patterns:
          - "*"
    pull-request-branch-name:
      separator: "-"
    labels:
      - "dependencies"
      - "python"
    reviewers:
      - "stilkin-pxl"

  - package-ecosystem: pip
    directory: "/applications/faq_tool"
    schedule:
      interval: daily
      time: "04:00"
    groups:
      python-packages:
        patterns:
          - "*"
    pull-request-branch-name:
      separator: "-"
    labels:
      - "dependencies"
      - "python"
    reviewers:
      - "stilkin-pxl"

  - package-ecosystem: pip
    directory: "/applications/chat_with_rag"
    schedule:
      interval: daily
      time: "04:00"
    groups:
      python-packages:
        patterns:
          - "*"
    pull-request-branch-name:
      separator: "-"
    labels:
      - "dependencies"
      - "python"
    reviewers:
      - "stilkin-pxl"

  - package-ecosystem: pip
    directory: "/demos/basic_chat"
    schedule:
      interval: daily
      time: "04:00"
    groups:
      python-packages:
        patterns:
          - "*"
    pull-request-branch-name:
      separator: "-"
    labels:
      - "dependencies"
      - "python"
    reviewers:
      - "stilkin-pxl"

  - package-ecosystem: pip
    directory: "/demos/tool_calling"
    schedule:
      interval: daily
      time: "04:00"
    groups:
      python-packages:
        patterns:
          - "*"
    pull-request-branch-name:
      separator: "-"
    labels:
      - "dependencies"
      - "python"
    reviewers:
      - "stilkin-pxl"

  - package-ecosystem: pip
    directory: "/demos/voice_notes"
    schedule:
      interval: daily
      time: "04:00"
    groups:
      python-packages:
        patterns:
          - "*"
    pull-request-branch-name:
      separator: "-"
    labels:
      - "dependencies"
      - "python"
    reviewers:
      - "stilkin-pxl"

  - package-ecosystem: pip
    directory: "/demos/rag"
    schedule:
      interval: daily
      time: "04:00"
    groups:
      python-packages:
        patterns:
          - "*"
    pull-request-branch-name:
      separator: "-"
    labels:
      - "dependencies"
      - "python"
    reviewers:
      - "stilkin-pxl"

  - package-ecosystem: pip
    directory: "/demos/model_choice"
    schedule:
      interval: daily
      time: "04:00"
    groups:
      python-packages:
        patterns:
          - "*"
    pull-request-branch-name:
      separator: "-"
    labels:
      - "dependencies"
      - "python"
    reviewers:
      - "stilkin-pxl"

  - package-ecosystem: pip
    directory: "/demos/slack_bot"
    schedule:
      interval: daily
      time: "04:00"
    groups:
      python-packages:
        patterns:
          - "*"
    pull-request-branch-name:
      separator: "-"
    labels:
      - "dependencies"
      - "python"
    reviewers:
      - "stilkin-pxl"

  - package-ecosystem: pip
    directory: "/demos/mcp_server_memory"
    schedule:
      interval: daily
      time: "04:00"
    groups:
      python-packages:
        patterns:
          - "*"
    pull-request-branch-name:
      separator: "-"
    labels:
      - "dependencies"
      - "python"
    reviewers:
      - "stilkin-pxl"

  - package-ecosystem: pip
    directory: "/demos/image_analysis"
    schedule:
      interval: daily
      time: "04:00"
    groups:
      python-packages:
        patterns:
          - "*"
    pull-request-branch-name:
      separator: "-"
    labels:
      - "dependencies"
      - "python"
    reviewers:
      - "stilkin-pxl"

  - package-ecosystem: pip
    directory: "/demos/mcp_server_file_io"
    schedule:
      interval: daily
      time: "04:00"
    groups:
      python-packages:
        patterns:
          - "*"
    pull-request-branch-name:
      separator: "-"
    labels:
      - "dependencies"
      - "python"
    reviewers:
      - "stilkin-pxl"
